[server]
listen_port = 3105
second_wait_login = 10
testmode = 0

[database]
host = "localhost"
port = 3306
database_name = "nro"
username = "root"
password = "ahwuocdz"
min_connections = 10
max_connections = 50
